# Generated by Django 2.2.4 on 2021-07-17 18:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Enter a valid mobile number', regex='^(\\+\\d{1,3}[- ]?)?\\d{10}$')])),
                ('team_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('level', models.IntegerField()),
                ('teamName', models.CharField(max_length=100)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Participant')),
            ],
        ),
    ]
