# Generated by Django 3.2.5 on 2021-07-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=20),
        ),
    ]
