# Generated by Django 2.2.4 on 2021-07-17 19:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='id',
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Team'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(),
        ),
    ]
