# Generated by Django 3.2.5 on 2021-07-18 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_participant_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Invalid email address', regex='^[A-Za-z0-9._~+-]+@thapar\\.edu$')]),
        ),
    ]
