# Generated by Django 3.2.5 on 2021-07-30 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_team_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='mobile',
        ),
        migrations.AddField(
            model_name='participant',
            name='discord_ID',
            field=models.CharField(default='', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid discord ID', regex='^.{3,32}#[0-9]{4}$')]),
        ),
    ]
