# Generated by Django 3.2.5 on 2021-08-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210731_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='level',
        ),
        migrations.AddField(
            model_name='participant',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
