# Generated by Django 3.2.5 on 2021-07-28 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qID', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('q_text', models.TextField()),
                ('q_image', models.ImageField(blank=True, upload_to='images/')),
                ('answer', models.CharField(max_length=200)),
                ('hint', models.TextField(blank=True)),
                ('is_dead_end', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_submitted', models.CharField(max_length=250)),
                ('time_when_submitted', models.DateTimeField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laberinto.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.team')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='leads_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_to', to='laberinto.room'),
        ),
        migrations.AddField(
            model_name='question',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laberinto.room'),
        ),
    ]
