# Generated by Django 3.2.5 on 2021-07-17 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qID', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('q_text', models.TextField()),
                ('q_image', models.ImageField(blank=True, upload_to='images/')),
                ('answer', models.CharField(max_length=200)),
                ('is_dead_end', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_submitted', models.CharField(max_length=250)),
                ('time_when_submitted', models.DateTimeField(blank=True, default=None, null=True)),
                ('qID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laberinto.question')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.team')),
            ],
        ),
    ]
