# Generated by Django 2.2.4 on 2021-07-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qID', models.IntegerField()),
                ('level', models.IntegerField()),
                ('points', models.IntegerField()),
                ('q_text', models.TextField()),
                ('answer', models.CharField(max_length=200)),
                ('is_dead_end', models.BooleanField(default=True)),
            ],
        ),
    ]
