# Generated by Django 3.2.5 on 2021-07-29 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laberinto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='leads_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads_to', to='laberinto.room'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_image',
            field=models.URLField(blank=True),
        ),
    ]
