# Generated by Django 3.2.5 on 2021-07-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laberinto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='team_id',
            new_name='team',
        ),
    ]
