# Generated by Django 3.2.5 on 2021-07-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laberinto', '0002_rename_team_id_submission_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='qID',
            new_name='question',
        ),
    ]
