# Generated by Django 3.2.5 on 2021-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laberinto', '0002_auto_20210729_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
