# Generated by Django 2.2.4 on 2021-07-17 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210718_0058'),
        ('laberinto', '0002_auto_20210718_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_submitted', models.CharField(max_length=250)),
                ('qID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='laberinto.Question')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.Team')),
            ],
        ),
    ]
