# Generated by Django 3.2.5 on 2021-08-07 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laberinto', '0003_alter_question_qid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='team',
        ),
        migrations.AddField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
